/**
 * AUTO-GENERATED FILE - DO NOT EDIT!
 *
 * This file was automatically generated by nestjs-trpc.
 * Any manual changes will be overwritten on the next generation.
 *
 * Command: `npx nestjs-trpc generate`
 * Learn more: https://nestjs-trpc.io
 */

import { initTRPC } from "@trpc/server";
import { z } from "zod";
import superjson from "superjson";

const t = initTRPC.create({ transformer: superjson });
const publicProcedure = t.procedure;
import { ContributorDetailSchema, ContributorsPageSchema } from "../modules/contributor/routers/../../../schema/openapi";
import { GameSearchResultSchema, CoverArtSchema, RatingCountsSchema, GamesPageSchema, GameByIdSchema, GamePricesSchema } from "../modules/game/routers/../../../schema/openapi";
import { PlayMethodEnum, PerformanceEnum, GraphicsSettingsEnum, TranslationLayerEnum } from "../modules/review/routers/../../../schema/index";
import { ChipsetVariantEnum, ChipsetEnum } from "../modules/game/routers/../../../schema/index";
import { LibraryLinkUrlSchema, LibraryStatusSchema, LibrarySyncResultSchema, LibraryEntrySchema, OkResultSchema } from "../modules/library/routers/../../../schema/openapi";
import { MyReviewsSchema, MacConfigSchema, UploadUrlSchema, CreateReviewResultSchema, MutationResultSchema } from "../modules/review/routers/../../../schema/openapi";
import type { ReviewRouter } from "../modules/review/routers/review.router";
import type { TrafficRouter } from "../modules/traffic/routers/traffic.router";

const appRouter = t.router({
  contributor: t.router({
    getById: publicProcedure
      .input(z.object({ id: z.string() }))
      .output(ContributorDetailSchema)
      .query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    getTopContributors: publicProcedure
      .input(z.object({
      limit: z.number().min(1).max(50).default(10),
      cursor: z.number().int().min(0).nullish(),
    }))
      .output(ContributorsPageSchema)
      .query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any)
    }),
  game: t.router({
    search: publicProcedure
      .input(z.object({ query: z.string() }))
      .output(z.array(GameSearchResultSchema))
      .query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    getCoverArt: publicProcedure
      .input(z.object({ gameId: z.string() }))
      .output(CoverArtSchema)
      .query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    getFilterCounts: publicProcedure
      .input(z.object({
      chipset: ChipsetEnum.optional(),
      chipsetVariant: ChipsetVariantEnum.optional(),
      playMethod: z.enum(['ALL', ...PlayMethodEnum.options]).default('ALL'),
    }))
      .output(RatingCountsSchema)
      .query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    getGames: publicProcedure
      .input(z.object({
      limit: z.number().min(1).max(50).default(6),
      cursor: z.number().min(0).default(0),
      performance: z.enum(['ALL', ...PerformanceEnum.options]).default('ALL'),
      chipset: ChipsetEnum.optional(),
      chipsetVariant: ChipsetVariantEnum.optional(),
      playMethod: z.enum(['ALL', ...PlayMethodEnum.options]).default('ALL'),
    }))
      .output(GamesPageSchema)
      .query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    getById: publicProcedure
      .input(z.object({ id: z.string() }))
      .output(GameByIdSchema)
      .query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    getScreenshotSignedUrls: publicProcedure
      .input(z.object({
      screenshots: z.preprocess(
        (value) => (typeof value === 'string' ? value.split(',') : value),
        z.array(z.string()),
      ),
    }))
      .output(z.array(z.object({ original: z.string(), signed: z.string() })))
      .query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    getPrices: publicProcedure
      .input(z.object({ gameId: z.string() }))
      .output(GamePricesSchema)
      .query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any)
    }),
  library: t.router({
    linkStartUrl: publicProcedure
      .input(z.void())
      .output(LibraryLinkUrlSchema)
      .query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    status: publicProcedure
      .input(z.void())
      .output(LibraryStatusSchema)
      .query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    sync: publicProcedure
      .input(z.void())
      .output(LibrarySyncResultSchema)
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    list: publicProcedure
      .input(z.void())
      .output(z.array(LibraryEntrySchema))
      .query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    unlink: publicProcedure
      .input(z.void())
      .output(OkResultSchema)
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any)
    }),
  review: t.router({
    getUserAuth: publicProcedure
      .query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as unknown as Awaited<ReturnType<ReviewRouter["getUserAuth"]>>),
    listMine: publicProcedure
      .input(z.void())
      .output(MyReviewsSchema)
      .query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    getMacConfigs: publicProcedure
      .input(z.object({
      search: z.string().optional(),
      selectedConfigIdentifier: z.string().optional(),
    }))
      .output(z.array(MacConfigSchema))
      .query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    getMacConfigById: publicProcedure
      .input(z.object({ identifier: z.string() }))
      .output(MacConfigSchema.nullable())
      .query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    getUploadUrl: publicProcedure
      .input(z.object({
      filename: z.string(),
      contentType: z.string(),
      gameId: z.string(),
    }))
      .output(UploadUrlSchema)
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    create: publicProcedure
      .input(z.object({
      gameId: z.string(),
      playMethod: PlayMethodEnum,
      translationLayer: TranslationLayerEnum.nullish(),
      performance: PerformanceEnum,
      fps: z.number().nullable().optional(),
      graphicsSettings: GraphicsSettingsEnum,
      resolution: z.string().optional(),
      macConfigIdentifier: z.string(),
      notes: z.string().optional(),
      screenshots: z.array(z.string()).optional(),
      softwareVersion: z.string().optional(),
    }))
      .output(CreateReviewResultSchema)
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    updateReview: publicProcedure
      .input(z.object({
      reviewId: z.string(),
      notes: z.string(),
      performance: PerformanceEnum.optional(),
      fps: z.number().nullable().optional(),
      resolution: z.string().nullable().optional(),
      softwareVersion: z.string().nullable().optional(),
      screenshots: z.array(z.string()).optional(),
    }))
      .output(MutationResultSchema)
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    deleteReview: publicProcedure
      .input(z.object({
      reviewId: z.string(),
      confirmation: z.boolean(),
    }))
      .output(MutationResultSchema)
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any)
    }),
  traffic: t.router({
    submitSource: publicProcedure
      .input(z.object({
      source: z.string().min(1).max(200),
      userAgent: z.string().optional(),
    }))
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as unknown as Awaited<ReturnType<TrafficRouter["submitSource"]>>)
    })
});

export type AppRouter = typeof appRouter;
