'use client';

import React, { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { toast } from 'sonner';
import { authClient } from '@/lib/auth/auth-client';

const SteamIcon = (props: React.SVGProps<SVGSVGElement>) => (
  <svg viewBox="0 0 24 24" fill="currentColor" {...props}>
    <path d="M11.979 0C5.666 0 .504 4.939.043 11.16L4.8 15.91a3.614 3.614 0 0 1 2.37-1.164l3.15-4.524a3.84 3.84 0 0 1-.03-.45c0-2.126 1.733-3.84 3.84-3.84 2.126 0 3.84 1.734 3.84 3.84 0 2.126-1.733 3.84-3.84 3.84-.27 0-.54-.045-.78-.105l-4.59 3.225a3.606 3.606 0 0 1-1.02 2.31l-4.71 4.71C4.414 23.511 8.014 24 11.979 24c6.627 0 12-5.373 12-12s-5.373-12-12-12zm2.13 7.8c1.104 0 1.98.876 1.98 1.98 0 1.104-.876 1.98-1.98 1.98-1.104 0-1.98-.876-1.98-1.98 0-1.104.876-1.98 1.98-1.98zM6.63 15.63c.69 0 1.26.57 1.26 1.26s-.57 1.26-1.26 1.26-1.26-.57-1.26-1.26.57-1.26 1.26-1.26zm1.14 1.26c0 1.05-.66 1.95-1.59 2.25l-1.35-1.35c.3-.93 1.2-1.59 2.25-1.59.39 0 .69.09.9.24-.12.15-.21.33-.21.54 0 .42.33.75.75.75.21 0 .39-.09.54-.21.15.21.24.51.24.9.03.03.03.06.03.09-.54-.51-1.05-1.05-1.56-1.62z" />
  </svg>
);

interface AuthPromptProps {
  /** Optional message to display above the form */
  promptMessage?: string;
  /** Style adjustments for embedding */
  className?: string;
  /** Style adjustments for the inner container */
  containerClassName?: string;
  /** External magic link sent state */
  magicLinkSent?: boolean;
  /** Callback when magic link is sent */
  onMagicLinkSent?: () => void;
}

export default function AuthPrompt({
  promptMessage = 'To combat spam, please log in to share your experience.',
  className = 'absolute inset-0 bg-black/20 flex flex-col items-center justify-center rounded-3xl p-6 z-10',
  containerClassName = 'bg-black border border-[#272727] p-6 rounded-xl',
  magicLinkSent: externalMagicLinkSent,
  onMagicLinkSent,
}: AuthPromptProps) {
  const { useSession, signIn } = authClient;

  const {
    data: session,
    isPending, //loading state
  } = useSession();

  const [email, setEmail] = useState('');
  const [isLoggingIn, setIsLoggingIn] = useState(false);
  const [isSteamLoading, setIsSteamLoading] = useState(false);
  const [internalMagicLinkSent, setInternalMagicLinkSent] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const magicLinkSent = externalMagicLinkSent ?? internalMagicLinkSent;

  const handleSteamLogin = async () => {
    setIsSteamLoading(true);
    setError(null);
    try {
      // Use the method generated by the steamAuthClient plugin
      const { data, error } = await signIn.steam({
        callbackURL: window.location.href,
      });

      if (error) {
        throw new Error(error.message || 'Failed to initialize Steam login');
      }

      // The server returns the Steam OpenID URL to redirect to
      if (data?.url) {
        window.location.href = data.url;
      }
    } catch (error) {
      setError('Error logging in with Steam. Please try again.');
      console.error(error);
      setIsSteamLoading(false);
    }
  };

  const handleLogin = async () => {
    if (!email || !email.includes('@')) {
      setError('Please enter a valid email address');
      return;
    }

    setIsLoggingIn(true);
    setError(null);

    try {
      await signIn.magicLink({
        email: email,
        callbackURL: window.location.href, //redirect after successful login (optional)
      });

      if (onMagicLinkSent) {
        onMagicLinkSent();
      } else {
        setInternalMagicLinkSent(true);
      }
      toast('Magic link sent to your email!');
    } catch (error) {
      setError('Error sending magic link. Please try again.');
      console.error(error);
    } finally {
      setIsLoggingIn(false);
    }
  };

  if (
    (typeof session?.user?.id !== 'undefined' || isPending) &&
    !magicLinkSent
  ) {
    return <></>;
  }

  return (
    <div
      className={className}
      style={{
        backdropFilter: 'blur(2px)',
        WebkitBackdropFilter: 'blur(2px)',
      }}
    >
      <div
        style={{ width: '100%', maxWidth: '24rem', margin: '0 auto' }}
        className={containerClassName}
      >
        <h3 className="text-xl font-bold mb-4">Login Required</h3>
        <p className="mb-6">{promptMessage}</p>

        {error && (
          <div className="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded mb-4">
            {error}
          </div>
        )}

        {magicLinkSent ? (
          <div className="text-center py-4">
            <p className="mb-2">✉️ Magic link sent!</p>
            <p className="text-sm text-gray-400">
              Check your email for a login link.
            </p>
          </div>
        ) : (
          <div className="space-y-4">
            <Button
              onClick={handleSteamLogin}
              className="w-full bg-[#171a21] hover:bg-[#1b1f28] text-white border border-[#2a475e] cursor-pointer"
              disabled={isSteamLoading || isLoggingIn}
              size="lg"
            >
              {isSteamLoading ? (
                'Connecting...'
              ) : (
                <>
                  <SteamIcon className="w-5 h-5 mr-2" />
                  Login with Steam
                </>
              )}
            </Button>

            <div className="relative py-2">
              <div className="absolute inset-0 flex items-center">
                <span className="w-full border-t border-gray-700" />
              </div>
              <div className="relative flex justify-center text-xs uppercase">
                <span className="bg-black px-2 text-gray-400">
                  Or with email
                </span>
              </div>
            </div>

            <div>
              <label className="block text-sm font-medium mb-1">
                Email Address
              </label>
              <Input
                type="email"
                value={email}
                onChange={(e) => setEmail(e.target.value)}
                placeholder="your@email.com"
                required
                className="bg-gray-800 border-gray-700 text-white placeholder-gray-500"
              />
            </div>
            <Button
              onClick={handleLogin}
              className="w-full"
              disabled={isLoggingIn || isSteamLoading}
              size="lg"
            >
              {isLoggingIn ? 'Sending Magic Link...' : 'Login with Magic Link'}
            </Button>
          </div>
        )}
      </div>
    </div>
  );
}